services:
  postgres:
    image: postgres:15
    container_name: loja-db
    environment:
      POSTGRES_USER: loja_user
      POSTGRES_PASSWORD: loja_pass
      POSTGRES_DB: loja_brinquedos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: loja-backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://loja_user:loja_pass@postgres:5432/loja_brinquedos
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      NODE_ENV: development
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: loja-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: