services:
  # Backend API
  - type: web
    name: avantsoft-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: avantsoft-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    
  # Frontend
  - type: web
    name: avantsoft-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://avantsoft-backend.onrender.com$1
      - type: rewrite
        source: /*
        destination: /index.html

# Database
databases:
  - name: avantsoft-db
    databaseName: avantsoft
    user: avantsoft_user
